apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-pod
  labels:
    app: hello-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-pod
  template:
    metadata:
      labels:
        app: hello-pod
    spec:
      containers:
      - image: gcr.io/tomcat-70998/jenkins-assignment:v1
        imagePullPolicy: Always
        name: hello-pod
        ports:
        - containerPort: 8080

